Support remote deployment
SubconsciousCompute/fsfilter-rs pull request #9
Opened 2023-04-15 11:29 UTC by olljanat

This pull request provides needed changes to support remote deployment to target machine directly from Visual Studio like example on [this](https://learn.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver#deploy-the-driver) guide.

Because this script uses `[DefaultInstall]` model in INF and does not register custom hardware ID deployment with `devcon.exe` whch Visual Studio uses by default does not works automatically so I solved it with custom script.

In additionally this PR will:
* Remove WDK version hardcoding and use latest one instead of.
* Use SHA256 as hash algorithm on code signing certificate which removes needed for boot test machine "Disable Driver Signature Enforcement" option.

Tested with Visual Studio 2019 but should works on VS2022 too.

2023-04-17 08:30 UTC, sn99 commented
@olljanat nice pr, just a few changes

2023-04-17 10:47 UTC, dilawar commented
Looks good to me @sn99

2023-04-18 08:27 UTC, sn99 requested changes

2023-04-18 08:27 UTC, sn99 commented on minifilter/snFilter/snFilter.vcxproj
> -    <WindowsTargetPlatformVersion>10.0.22621.0</WindowsTargetPlatformVersion>
Can we revert back to fixed version, the reasoning it that there might be bugs or changes from version to version and everyone might not be on same "latest" version. This also makes debugging difficult.

2023-04-18 09:44 UTC, olljanat commented on minifilter/snFilter/snFilter.vcxproj
> -    <WindowsTargetPlatformVersion>10.0.22621.0</WindowsTargetPlatformVersion>
Ok. Good to know. Then I will switch to that version too. PR updated

2023-04-20 04:40 UTC, sn99 approved these changes

2023-04-20 04:41 UTC, merged